# Generated by Django 4.0.1 on 2022-06-05 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prof_type', models.CharField(choices=[('TP', 'Teaching Prof'), ('RP', 'Research Prof'), ('OT', 'Other')], default='TP', max_length=2)),
            ],
            options={
                'db_table': 'appuser',
                'managed': True,
            },
        ),
    ]