# Generated by Django 4.0.1 on 2022-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_peng',
            field=models.BooleanField(default=False),
        ),
    ]
