# Generated by Django 4.0.1 on 2022-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_is_peng'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_form_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
