version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    command: python manage.py runserver 0.0.0.0:8000
    container_name: scheduler_service
    volumes:
      - .:/home/app/web
    ports:
      - "8000:8000"
    restart: on-failure
