# Generated by Django 4.0.1 on 2022-06-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0002_appuser_is_peng'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('SPRING', 'Spring Semester'), ('SUMMER', 'Summer Semester'), ('FALL', 'Fall Semester')], max_length=6)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=9)),
                ('startTime', models.CharField(max_length=7)),
                ('endTime', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('isPeng', models.BooleanField(default=False)),
                ('facultyType', models.CharField(choices=[('TP', 'Teaching Prof'), ('RP', 'Research Prof'), ('OT', 'Other')], default='TP', max_length=2)),
                ('teachingObligations', models.IntegerField()),
                ('coursePreferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('preferredTimes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.preferredtime')),
                ('userData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
        ),
    ]
