# Generated by Django 4.0.1 on 2022-06-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_appuser_is_peng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.appuser')),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_unavailable_sem1', models.BooleanField(default=False)),
                ('is_unavailable_sem2', models.BooleanField(default=False)),
                ('num_relief_courses', models.PositiveIntegerField(default=0)),
                ('taking_sabbatical', models.BooleanField(default=False)),
                ('sabbatical_length', models.CharField(choices=[('HALF', 'Half Length'), ('FULL', 'Full Length'), ('NONE', 'None')], default='NONE', max_length=4)),
                ('sabbatical_start_month', models.PositiveIntegerField(default=0)),
                ('preferred_hours', models.JSONField()),
                ('teaching_willingness', models.JSONField()),
                ('teaching_difficulty', models.JSONField()),
                ('wants_topics_course', models.BooleanField(default=False)),
                ('topics_course_id', models.CharField(blank=True, default='', max_length=20)),
                ('topics_course_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'preferences',
                'managed': True,
            },
        ),
    ]
