# Generated by Django 4.0.1 on 2022-06-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='is_completed',
            new_name='is_submitted',
        ),
        migrations.AlterModelTable(
            name='preferences',
            table='preferences',
        ),
    ]
