# Generated by Django 4.0.1 on 2022-06-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_preferences_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='user_id',
            new_name='appuser',
        ),
    ]
