# Generated by Django 4.0.1 on 2022-07-09 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_preferences_preferred_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='preferred_hours',
            new_name='preferred_times',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='is_unavailable_sem1',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='is_unavailable_sem2',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='num_relief_courses',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='teaching_difficulty',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='teaching_willingness',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='topics_course_id',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='topics_course_name',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='wants_topics_course',
        ),
        migrations.AddField(
            model_name='preferences',
            name='courses_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='preferences',
            name='preferred_course_day_spreads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None),
        ),
        migrations.AddField(
            model_name='preferences',
            name='preferred_courses_per_semester',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='preferences',
            name='preferred_non_teaching_semester',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='preferences',
            name='preferred_number_teaching_days',
            field=models.JSONField(default=dict),
        ),
    ]
