# Generated by Django 4.0.1 on 2022-07-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_rename_preferred_hours_preferences_preferred_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='preferred_number_teaching_days',
        ),
    ]
