# Generated by Django 4.0.1 on 2022-07-29 06:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_remove_preferences_preferred_number_teaching_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='courses_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferred_course_day_spreads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferred_courses_per_semester',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferred_times',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
