# Generated by Django 4.0.1 on 2022-06-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_alter_preferences_num_relief_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='num_relief_courses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
