# Generated by Django 4.0.1 on 2022-06-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_alter_preferences_num_relief_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='appuser',
            new_name='professor',
        ),
        migrations.AlterField(
            model_name='preferences',
            name='sabbatical_start_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
