# Generated by Django 4.0.1 on 2022-07-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_coursesection',
            name='professor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
