# Generated by Django 4.0.1 on 2022-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_course',
            name='yearRequired',
            field=models.CharField(max_length=5),
        ),
    ]
