# Generated by Django 4.0.1 on 2022-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_a_course_yearrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_courseoffering',
            name='course',
            field=models.ManyToManyField(related_name='courseOfferings', to='schedule.A_Course'),
        ),
        migrations.AlterField(
            model_name='a_courseoffering',
            name='sections',
            field=models.ManyToManyField(related_name='courseOfferings', to='schedule.A_CourseSection'),
        ),
        migrations.AlterField(
            model_name='a_coursesection',
            name='timeSlots',
            field=models.ManyToManyField(related_name='courseSections', to='schedule.A_TimeSlot'),
        ),
        migrations.AlterField(
            model_name='a_schedule',
            name='fall',
            field=models.ManyToManyField(related_name='fall_schedules', to='schedule.A_CourseOffering'),
        ),
        migrations.AlterField(
            model_name='a_schedule',
            name='spring',
            field=models.ManyToManyField(related_name='spring_schedules', to='schedule.A_CourseOffering'),
        ),
        migrations.AlterField(
            model_name='a_schedule',
            name='summer',
            field=models.ManyToManyField(related_name='summer_schedules', to='schedule.A_CourseOffering'),
        ),
    ]
