# Generated by Django 4.0.1 on 2022-07-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_a_courseoffering_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_courseoffering',
            name='course',
        ),
        migrations.AddField(
            model_name='a_courseoffering',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseOfferings', to='schedule.a_course'),
        ),
    ]
