# Generated by Django 4.0.1 on 2022-07-06 22:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_a_courseoffering_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_timeslot',
            name='timeRange',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), size=2),
        ),
    ]
