# Generated by Django 4.0.1 on 2022-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('num_sections', models.PositiveIntegerField(default=1)),
                ('course_title', models.TextField()),
                ('fall_offering', models.BooleanField(default=False)),
                ('spring_offering', models.BooleanField(default=False)),
                ('summer_offering', models.BooleanField(default=False)),
                ('pengRequired', models.JSONField(default=dict)),
                ('yearRequired', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'Courses',
                'managed': True,
            },
        ),
    ]
