# Generated by Django 4.0.1 on 2022-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='yearRequired',
            field=models.IntegerField(default=4),
        ),
    ]
