# Generated by Django 4.0.1 on 2022-07-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_fall_sections_course_spring_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fall_offering',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_sections',
        ),
        migrations.RemoveField(
            model_name='course',
            name='spring_offering',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summer_offering',
        ),
    ]
